<?php

namespace Database\Seeders;

use App\Models\Division;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DivisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $divisions = [
            ['division_id' => 0, 'division_name_ar' => 'الجيزه لصناعة الكابلات', 'division_name_en' => 'Giza Cables Industry', 'parent_division_id' => NULL,],
            ['division_id' => 1, 'division_name_ar' => 'المكتب الرئيسى', 'division_name_en' => 'Head Office', 'parent_division_id' => 0,],
            ['division_id' => 2, 'division_name_ar' => 'مصنع الجهد المنخفض', 'division_name_en' => 'Low Voltage Factory', 'parent_division_id' => 0,],
            ['division_id' => 3, 'division_name_ar' => 'مصنع الجهد المتوسط', 'division_name_en' => 'Medium Voltage Factory', 'parent_division_id' => 0,],
            ['division_id' => 4, 'division_name_ar' => 'معرض 6 أكتوبر', 'division_name_en' => '6th of October Exhibition', 'parent_division_id' => 0,],
            ['division_id' => 11, 'division_name_ar' => 'الادارة العليا للمكتب الرئيسي', 'division_name_en' => 'Head Office Senior Management', 'parent_division_id' => 1,],
            ['division_id' => 12, 'division_name_ar' => 'الادارة المالية', 'division_name_en' => 'Financial Management', 'parent_division_id' => 1,],
            ['division_id' => 13, 'division_name_ar' => 'الادارة العامة للمبيعات', 'division_name_en' => 'Sales General Management', 'parent_division_id' => 1,],
            ['division_id' => 14, 'division_name_ar' => 'ادارة الشئون القانونية', 'division_name_en' => 'Legal Affairs Department', 'parent_division_id' => 1,],
            ['division_id' => 15, 'division_name_ar' => 'ادارة الموارد البشرية', 'division_name_en' => 'Human Resources Department', 'parent_division_id' => 1,],
            ['division_id' => 16, 'division_name_ar' => 'إدارة سلسلة الأمدادات', 'division_name_en' => 'Supply Chain Management', 'parent_division_id' => 1,],
            ['division_id' => 17, 'division_name_ar' => 'ادارة تكنولوجيا المعلومات', 'division_name_en' => 'Information Technology Department', 'parent_division_id' => 1,],
            ['division_id' => 18, 'division_name_ar' => 'قسم الشئون الادارية', 'division_name_en' => 'Administrative Affairs Department', 'parent_division_id' => 15,],
            ['division_id' => 20, 'division_name_ar' => 'ادارة تكتولوجيا المعلومات', 'division_name_en' => 'Information Technology Department', 'parent_division_id' => 2,],
            ['division_id' => 21, 'division_name_ar' => 'الادارة المالية لمصنع الجهد المنخفض', 'division_name_en' => 'Financial Management of Low Voltage Plant', 'parent_division_id' => 2,],
            ['division_id' => 22, 'division_name_ar' => 'ادارة سلسلة الأمدادات بمصنع الجهد المنخفض', 'division_name_en' => 'Supply Chain Management of Low Voltage Plant', 'parent_division_id' => 2,],
            ['division_id' => 51, 'division_name_ar' => 'الادارة العليا لمصنع الجهد المنخفض', 'division_name_en' => 'Senior Management of Low Voltage Plant', 'parent_division_id' => 2,],
            ['division_id' => 52, 'division_name_ar' => 'ادارة التخطيط', 'division_name_en' => 'Planning Department', 'parent_division_id' => 2,],
            ['division_id' => 53, 'division_name_ar' => 'ادارة الانتاج', 'division_name_en' => 'Production Department', 'parent_division_id' => 2,],
            ['division_id' => 54, 'division_name_ar' => 'ادارة الجودة', 'division_name_en' => 'Quality Management', 'parent_division_id' => 2,],
            ['division_id' => 55, 'division_name_ar' => 'الادارة العامة للصيانة', 'division_name_en' => 'General Maintenance Department', 'parent_division_id' => 2,],
            ['division_id' => 56, 'division_name_ar' => 'ادارة توكيد الجودة', 'division_name_en' => 'Quality Assurance Department', 'parent_division_id' => 2,],
            ['division_id' => 57, 'division_name_ar' => 'ادارة الشئون الادارية', 'division_name_en' => 'Administrative Affairs Department', 'parent_division_id' => 61,],
            ['division_id' => 58, 'division_name_ar' => 'ادارة المخازن', 'division_name_en' => 'Warehouse Management', 'parent_division_id' => 22,],
            ['division_id' => 59, 'division_name_ar' => 'ادارة خدمة العملاء', 'division_name_en' => 'Customer Service Department', 'parent_division_id' => 2,],
            ['division_id' => 60, 'division_name_ar' => 'ادارة المواصفات الفنية', 'division_name_en' => 'Technical Specifications Department', 'parent_division_id' => 2,],
            ['division_id' => 61, 'division_name_ar' => 'ادارة الموارد البشرية بمصنع الجهد المنخفض', 'division_name_en' => 'Human Resources Department of Low Voltage Plant', 'parent_division_id' => 2,],
            ['division_id' => 62, 'division_name_ar' => 'إدارة الأمن الإدارى', 'division_name_en' => 'Administrative Security Department', 'parent_division_id' => 2,],
            ['division_id' => 100, 'division_name_ar' => 'الادارة العليا لمصنع الجهد المتوسط', 'division_name_en' => 'Senior Management of Medium Voltage Plant', 'parent_division_id' => 3,],
            ['division_id' => 101, 'division_name_ar' => 'الادارة المالية لمصنع الجهد المتوسط', 'division_name_en' => 'Financial Management of Medium Voltage Plant', 'parent_division_id' => 3,],
            ['division_id' => 102, 'division_name_ar' => 'ادارة التخطيط', 'division_name_en' => 'Planning Department', 'parent_division_id' => 3,],
            ['division_id' => 103, 'division_name_ar' => 'ادارة الانتاج', 'division_name_en' => 'Production Department', 'parent_division_id' => 3,],
            ['division_id' => 104, 'division_name_ar' => 'ادارة الجودة', 'division_name_en' => 'Quality Management', 'parent_division_id' => 3,],
            ['division_id' => 105, 'division_name_ar' => 'ادارة الصيانة', 'division_name_en' => 'Maintenance Department', 'parent_division_id' => 3,],
            ['division_id' => 106, 'division_name_ar' => 'ادارة توكيد الجودة', 'division_name_en' => 'Quality Assurance Department', 'parent_division_id' => 3,],
            ['division_id' => 107, 'division_name_ar' => 'ادارة الشئون الادارية', 'division_name_en' => 'Administrative Affairs Department', 'parent_division_id' => 115,],
            ['division_id' => 108, 'division_name_ar' => 'ادارة المخازن', 'division_name_en' => 'Warehouse Management', 'parent_division_id' => 121,],
            ['division_id' => 109, 'division_name_ar' => 'ادارة خدمة العملاء', 'division_name_en' => 'Customer Service Department', 'parent_division_id' => 3,],
            ['division_id' => 110, 'division_name_ar' => 'ادارة المواصفات الفنية', 'division_name_en' => 'Technical Specifications Department', 'parent_division_id' => 3,],
            ['division_id' => 111, 'division_name_ar' => 'قسم المعادن', 'division_name_en' => 'Metals Department', 'parent_division_id' => 103,],
            ['division_id' => 112, 'division_name_ar' => 'قسم العزل والغلاف', 'division_name_en' => 'Insulation and Sheathing Department', 'parent_division_id' => 103,],
            ['division_id' => 113, 'division_name_ar' => 'قسم التجميع والتسليح', 'division_name_en' => 'Assembly and Reinforcement Department', 'parent_division_id' => 103,],
            ['division_id' => 115, 'division_name_ar' => 'ادارة الموارد البشرية بمصنع الجهد المتوسط', 'division_name_en' => 'Human Resources Management in Medium Voltage Plant', 'parent_division_id' => 3,],
            ['division_id' => 120, 'division_name_ar' => 'ادارة تكنولوجيا المعلومات', 'division_name_en' => 'Information Technology Management', 'parent_division_id' => 3,],
            ['division_id' => 121, 'division_name_ar' => 'ادارة سلسلة الأمدادات بمصنع الجهد المتوسط', 'division_name_en' => 'Supply Chain Management in Medium Voltage Plant', 'parent_division_id' => 3,],
            ['division_id' => 151, 'division_name_ar' => 'قسم المالية', 'division_name_en' => 'Finance Department', 'parent_division_id' => 12,],
            ['division_id' => 152, 'division_name_ar' => 'قسم التكاليف', 'division_name_en' => 'Cost Department', 'parent_division_id' => 12,],
            ['division_id' => 160, 'division_name_ar' => 'ادارة المبيعات المحلية', 'division_name_en' => 'Local Sales Department', 'parent_division_id' => 13,],
            ['division_id' => 161, 'division_name_ar' => 'ادارة تطوير الاعمال', 'division_name_en' => 'Business Development Department', 'parent_division_id' => 13,],
            ['division_id' => 170, 'division_name_ar' => 'قسم التوظيف والتدريب', 'division_name_en' => 'Recruitment and Training Department', 'parent_division_id' => 15,],
            ['division_id' => 171, 'division_name_ar' => 'قسم المشتريات المحلية', 'division_name_en' => 'Local Purchasing Department', 'parent_division_id' => 16,],
            ['division_id' => 172, 'division_name_ar' => 'قسم المشتريات الخارجية', 'division_name_en' => 'External Purchasing Department', 'parent_division_id' => 16,],
            ['division_id' => 173, 'division_name_ar' => 'قسم المرتبات', 'division_name_en' => 'Payroll Department', 'parent_division_id' => 15,],
            ['division_id' => 175, 'division_name_ar' => 'قسم تنسيق الموارد البشرية', 'division_name_en' => 'Human Resources Coordination Department', 'parent_division_id' => 15,],
            ['division_id' => 186, 'division_name_ar' => 'شبكات', 'division_name_en' => 'Networks', 'parent_division_id' => 17,],
            ['division_id' => 187, 'division_name_ar' => 'برمجة', 'division_name_en' => 'Programming', 'parent_division_id' => 17,],
            ['division_id' => 188, 'division_name_ar' => 'قواعد بيانات', 'division_name_en' => 'Databases', 'parent_division_id' => 17,],
            ['division_id' => 190, 'division_name_ar' => 'قسم خدمات معاونة', 'division_name_en' => 'Support Services Department', 'parent_division_id' => 18,],
            ['division_id' => 191, 'division_name_ar' => 'قسم سكرتارية', 'division_name_en' => 'Secretarial Department', 'parent_division_id' => 18,],
            ['division_id' => 192, 'division_name_ar' => 'قسم السائقين', 'division_name_en' => 'Drivers Department', 'parent_division_id' => 18,],
            ['division_id' => 200, 'division_name_ar' => 'قسم الحسابات', 'division_name_en' => 'Accounts Department', 'parent_division_id' => 21,],
            ['division_id' => 201, 'division_name_ar' => 'قسم تخطيط الخامات', 'division_name_en' => 'Material Planning Department', 'parent_division_id' => 52,],
            ['division_id' => 202, 'division_name_ar' => 'قسم متابعة الانتاج', 'division_name_en' => 'Production Follow-up Department', 'parent_division_id' => 52,],
            ['division_id' => 206, 'division_name_ar' => 'ورنيش', 'division_name_en' => 'Varnish', 'parent_division_id' => 53,],
            ['division_id' => 207, 'division_name_ar' => 'تليفونات', 'division_name_en' => 'Telephones', 'parent_division_id' => 53,],
            ['division_id' => 208, 'division_name_ar' => 'كابلات باور', 'division_name_en' => 'Power Cables', 'parent_division_id' => 53,],
            ['division_id' => 210, 'division_name_ar' => 'اختبارات', 'division_name_en' => 'Tests', 'parent_division_id' => 54,],
            ['division_id' => 211, 'division_name_ar' => 'مراجعة', 'division_name_en' => 'Review', 'parent_division_id' => 617,],
            ['division_id' => 215, 'division_name_ar' => 'ادارة المشروعات', 'division_name_en' => 'Project Management', 'parent_division_id' => 55,],
            ['division_id' => 216, 'division_name_ar' => 'ادارة الصيانة الكهربائية', 'division_name_en' => 'Electrical Maintenance Department', 'parent_division_id' => 55,],
            ['division_id' => 217, 'division_name_ar' => 'ادارة الصيانة الميكانيكية', 'division_name_en' => 'Mechanical Maintenance Department', 'parent_division_id' => 55,],
            ['division_id' => 218, 'division_name_ar' => 'قسم تبريد وتكييف', 'division_name_en' => 'Cooling and Air Conditioning Department', 'parent_division_id' => 216,],
            ['division_id' => 219, 'division_name_ar' => 'قسم المرافق', 'division_name_en' => 'Facilities Department', 'parent_division_id' => 55,],
            ['division_id' => 220, 'division_name_ar' => 'قسم الفوركلفت وصيانة الحركة والنقل', 'division_name_en' => 'Forklift and Movement and Transportation Maintenance Department', 'parent_division_id' => 2,],
            ['division_id' => 226, 'division_name_ar' => 'قسم المراجعة الداخلية وضبط الوثائق', 'division_name_en' => 'Internal Audit and Document Control Department', 'parent_division_id' => 56,],
            ['division_id' => 231, 'division_name_ar' => 'قسم التأمينات', 'division_name_en' => 'Insurance Department', 'parent_division_id' => 57,],
            ['division_id' => 232, 'division_name_ar' => 'قسم شئون العاملين', 'division_name_en' => 'Personnel Affairs Department', 'parent_division_id' => 61,],
            ['division_id' => 233, 'division_name_ar' => 'قسم السلامة وصحة مهنية', 'division_name_en' => 'Occupational Safety and Health Department', 'parent_division_id' => 2,],
            ['division_id' => 234, 'division_name_ar' => 'قسم الشئون القانونية بالمصنع', 'division_name_en' => 'Factory Legal Affairs Department', 'parent_division_id' => 2,],
            ['division_id' => 235, 'division_name_ar' => 'قسم الحملة', 'division_name_en' => 'Campaign Department', 'parent_division_id' => 57,],
            ['division_id' => 236, 'division_name_ar' => 'قسم الأمن الإدارى', 'division_name_en' => 'Administrative Security Department', 'parent_division_id' => 62,],
            ['division_id' => 237, 'division_name_ar' => 'قسم خدمات معاونة', 'division_name_en' => 'Auxiliary Services Department', 'parent_division_id' => 57,],
            ['division_id' => 238, 'division_name_ar' => 'قسم سكرتارية', 'division_name_en' => 'Secretarial Department', 'parent_division_id' => 57,],
            ['division_id' => 240, 'division_name_ar' => 'ادارة المشتريات', 'division_name_en' => 'Purchasing Department', 'parent_division_id' => 22,],
            ['division_id' => 241, 'division_name_ar' => 'قسم مخازن الخامات', 'division_name_en' => 'Raw Materials Stores Department', 'parent_division_id' => 58,],
            ['division_id' => 242, 'division_name_ar' => 'قسم مخازن قطع الغيار', 'division_name_en' => 'Spare Parts Stores Department', 'parent_division_id' => 58,],
            ['division_id' => 246, 'division_name_ar' => 'قسم خدمة العملاء', 'division_name_en' => 'Customer Service Department', 'parent_division_id' => 59,],
            ['division_id' => 248, 'division_name_ar' => 'قسم المعادن', 'division_name_en' => 'Metals Department', 'parent_division_id' => 208,],
            ['division_id' => 249, 'division_name_ar' => 'قسم العزل والغلاف', 'division_name_en' => 'Insulation and Covering Department', 'parent_division_id' => 208,],
            ['division_id' => 250, 'division_name_ar' => 'قسم التجميع والتسليح', 'division_name_en' => 'Assembly and Reinforcement Department', 'parent_division_id' => 208,],
            ['division_id' => 300, 'division_name_ar' => 'قسم الحسابات', 'division_name_en' => 'Accounts Department', 'parent_division_id' => 101,],
            ['division_id' => 301, 'division_name_ar' => 'قسم تخطيط الخامات', 'division_name_en' => 'Raw Materials Planning Department', 'parent_division_id' => 102,],
            ['division_id' => 302, 'division_name_ar' => 'قسم متابعة الانتاج', 'division_name_en' => 'Production Follow-up Department', 'parent_division_id' => 102,],
            ['division_id' => 306, 'division_name_ar' => 'قسم CVL', 'division_name_en' => 'CVL Department', 'parent_division_id' => 103,],
            ['division_id' => 307, 'division_name_ar' => 'سحب', 'division_name_en' => 'Withdrawal', 'parent_division_id' => 111,],
            ['division_id' => 308, 'division_name_ar' => 'جدل', 'division_name_en' => 'Arranging', 'parent_division_id' => 111,],
            ['division_id' => 309, 'division_name_ar' => 'عزل', 'division_name_en' => 'Insulation', 'parent_division_id' => 112,],
            ['division_id' => 310, 'division_name_ar' => 'غلاف', 'division_name_en' => 'Covering', 'parent_division_id' => 112,],
            ['division_id' => 311, 'division_name_ar' => 'تسليح', 'division_name_en' => 'Reinforcement', 'parent_division_id' => 113,],
            ['division_id' => 312, 'division_name_ar' => 'تجميع', 'division_name_en' => 'Assembly', 'parent_division_id' => 113,],
            ['division_id' => 313, 'division_name_ar' => 'تقطيع', 'division_name_en' => 'Cutting', 'parent_division_id' => 112,],
            ['division_id' => 314, 'division_name_ar' => 'قسم المراجعة', 'division_name_en' => 'Audit Department', 'parent_division_id' => 103,],
            ['division_id' => 315, 'division_name_ar' => 'ادارة المشروعات', 'division_name_en' => 'Project Management', 'parent_division_id' => 105,],
            ['division_id' => 321, 'division_name_ar' => 'اختبارات', 'division_name_en' => 'Tests', 'parent_division_id' => 104,],
            ['division_id' => 322, 'division_name_ar' => 'مراجعة', 'division_name_en' => 'Review', 'parent_division_id' => 314,],
            ['division_id' => 323, 'division_name_ar' => 'قسم الرصاص', 'division_name_en' => 'Lead Department', 'parent_division_id' => 103,],
            ['division_id' => 326, 'division_name_ar' => 'ادارة الصيانة الكهربائية', 'division_name_en' => 'Electrical Maintenance Department', 'parent_division_id' => 105,],
            ['division_id' => 327, 'division_name_ar' => 'ادارة الصيانة الميكانيكية', 'division_name_en' => 'Mechanical Maintenance Department', 'parent_division_id' => 105,],
            ['division_id' => 328, 'division_name_ar' => 'تبريد وتكييف', 'division_name_en' => 'Cooling and Air Conditioning', 'parent_division_id' => 326,],
            ['division_id' => 329, 'division_name_ar' => 'قسم المرافق', 'division_name_en' => 'Facilities Department', 'parent_division_id' => 105,],
            ['division_id' => 330, 'division_name_ar' => 'قسم الفوركلفت وصيانة الحركة والنقل', 'division_name_en' => 'Forklift and Movement and Transportation Maintenance Department', 'parent_division_id' => 3,],
            ['division_id' => 336, 'division_name_ar' => 'قسم المراجعة الداخلية وضبط الوثائق', 'division_name_en' => 'Internal Audit and Document Control Department', 'parent_division_id' => 106,],
            ['division_id' => 342, 'division_name_ar' => 'قسم التأمينات', 'division_name_en' => 'Insurance Department', 'parent_division_id' => 107,],
            ['division_id' => 343, 'division_name_ar' => 'قسم شئون العاملين', 'division_name_en' => 'Personnel Affairs Department', 'parent_division_id' => 107,],
            ['division_id' => 344, 'division_name_ar' => 'قسم السلامة وصحة مهنية', 'division_name_en' => 'Occupational Safety and Health Department', 'parent_division_id' => 3,],
            ['division_id' => 345, 'division_name_ar' => 'قسم الشئون القانونية بالمصنع', 'division_name_en' => 'Factory Legal Affairs Department', 'parent_division_id' => 3,],
            ['division_id' => 346, 'division_name_ar' => 'قسم الحملة', 'division_name_en' => 'Campaign Department', 'parent_division_id' => 107,],
            ['division_id' => 347, 'division_name_ar' => 'قسم الأمن الإدارى', 'division_name_en' => 'Administrative Security Department', 'parent_division_id' => 620,],
            ['division_id' => 348, 'division_name_ar' => 'قسم خدمات معاونة', 'division_name_en' => 'Auxiliary Services Department', 'parent_division_id' => 107,],
            ['division_id' => 349, 'division_name_ar' => 'قسم السكرتارية', 'division_name_en' => 'Secretarial Department', 'parent_division_id' => 107,],
            ['division_id' => 350, 'division_name_ar' => 'ادارة المشتريات', 'division_name_en' => 'Purchasing Department', 'parent_division_id' => 121,],
            ['division_id' => 351, 'division_name_ar' => 'قسم مخازن الخامات', 'division_name_en' => 'Raw Materials Stores Department', 'parent_division_id' => 108,],
            ['division_id' => 352, 'division_name_ar' => 'قسم مخازن قطع الغيار', 'division_name_en' => 'Spare Parts Stores Department', 'parent_division_id' => 108,],
            ['division_id' => 356, 'division_name_ar' => 'قسم خدمة العملاء', 'division_name_en' => 'Customer Service Department', 'parent_division_id' => 109,],
            ['division_id' => 357, 'division_name_ar' => 'قسم مخازن الانتاج التام', 'division_name_en' => 'Finished Production Stores Department', 'parent_division_id' => 109,],
            ['division_id' => 400, 'division_name_ar' => 'قسم الجمارك', 'division_name_en' => 'Customs Department', 'parent_division_id' => 16,],
            ['division_id' => 401, 'division_name_ar' => 'قسم التحصيلات', 'division_name_en' => 'Collections Department', 'parent_division_id' => 151,],
            ['division_id' => 402, 'division_name_ar' => 'قسم السكرتارية والتشهيلات', 'division_name_en' => 'Secretarial and Facilities Department', 'parent_division_id' => 151,],
            ['division_id' => 403, 'division_name_ar' => 'قسم الحسابات', 'division_name_en' => 'Accounts Department', 'parent_division_id' => 151,],
            ['division_id' => 415, 'division_name_ar' => 'قسم المبيعات التجارية', 'division_name_en' => 'Commercial Sales Department', 'parent_division_id' => 160,],
            ['division_id' => 416, 'division_name_ar' => 'قسم مبيعات وزارة الكهرباء', 'division_name_en' => 'Electricity Ministry Sales Department', 'parent_division_id' => 160,],
            ['division_id' => 417, 'division_name_ar' => 'قسم مبيعات المشروعات', 'division_name_en' => 'Project Sales Department', 'parent_division_id' => 160,],
            ['division_id' => 418, 'division_name_ar' => 'قسم حسابات المبيعات', 'division_name_en' => 'Sales Accounts Department', 'parent_division_id' => 160,],
            ['division_id' => 419, 'division_name_ar' => 'قسم مبيعات الورنيش', 'division_name_en' => 'Varnish Sales Department', 'parent_division_id' => 160,],
            ['division_id' => 420, 'division_name_ar' => 'منافذ البيع', 'division_name_en' => 'Sales Outlets', 'parent_division_id' => 160,],
            ['division_id' => 425, 'division_name_ar' => 'قسم التسويق', 'division_name_en' => 'Marketing Department', 'parent_division_id' => 161,],
            ['division_id' => 435, 'division_name_ar' => 'قسم انتاج الورنيش', 'division_name_en' => 'Varnish Production Department', 'parent_division_id' => 206,],
            ['division_id' => 436, 'division_name_ar' => 'قسم جودة الورنيش', 'division_name_en' => 'Varnish Quality Department', 'parent_division_id' => 206,],
            ['division_id' => 437, 'division_name_ar' => 'قسم الفيلارات', 'division_name_en' => 'Filers Department', 'parent_division_id' => 206,],
            ['division_id' => 445, 'division_name_ar' => 'سحب التليفونات', 'division_name_en' => 'Telephone Withdrawal', 'parent_division_id' => 207,],
            ['division_id' => 446, 'division_name_ar' => 'جدل التليفونات', 'division_name_en' => 'Telephone Stringing', 'parent_division_id' => 207,],
            ['division_id' => 447, 'division_name_ar' => 'عزل التليفونات', 'division_name_en' => 'Telephone Insulation', 'parent_division_id' => 207,],
            ['division_id' => 448, 'division_name_ar' => 'غلاف التليفونات', 'division_name_en' => 'Telephone Covering', 'parent_division_id' => 207,],
            ['division_id' => 449, 'division_name_ar' => 'تسليح التليفونات', 'division_name_en' => 'Telephone Armoring', 'parent_division_id' => 207,],
            ['division_id' => 450, 'division_name_ar' => 'تجميع التليفونات', 'division_name_en' => 'Telephone Assembly', 'parent_division_id' => 207,],
            ['division_id' => 451, 'division_name_ar' => 'تقطيع التليفونات', 'division_name_en' => 'Telephone Cutting', 'parent_division_id' => 207,],
            ['division_id' => 452, 'division_name_ar' => 'مراجعة التليفونات', 'division_name_en' => 'Telephone Review', 'parent_division_id' => 207,],
            ['division_id' => 460, 'division_name_ar' => 'قسم التركيبات الميكانيكية', 'division_name_en' => 'Mechanical Installations Department', 'parent_division_id' => 215,],
            ['division_id' => 461, 'division_name_ar' => 'قسم التركيبات الكهربائية', 'division_name_en' => 'Electrical Installations Department', 'parent_division_id' => 215,],
            ['division_id' => 465, 'division_name_ar' => 'قسم لحام', 'division_name_en' => 'Welding Department', 'parent_division_id' => 219,],
            ['division_id' => 466, 'division_name_ar' => 'قسم النجارة', 'division_name_en' => 'Carpentry Department', 'parent_division_id' => 53,],
            ['division_id' => 467, 'division_name_ar' => 'قسم الدهانات', 'division_name_en' => 'Painting Department', 'parent_division_id' => 219,],
            ['division_id' => 468, 'division_name_ar' => 'قسم الخراطة', 'division_name_en' => 'Lathe Department', 'parent_division_id' => 219,],
            ['division_id' => 476, 'division_name_ar' => 'قسم مخازن الانتاج التام', 'division_name_en' => 'Full Production Stores Department', 'parent_division_id' => 59,],
            ['division_id' => 477, 'division_name_ar' => 'صيانة المرافق', 'division_name_en' => 'Facility Maintenance', 'parent_division_id' => 219,],
            ['division_id' => 500, 'division_name_ar' => 'قسم التركيبات الميكانيكية', 'division_name_en' => 'Mechanical Installations Department', 'parent_division_id' => 315,],
            ['division_id' => 501, 'division_name_ar' => 'قسم التركيبات الكهربائية', 'division_name_en' => 'Electrical Installations Department', 'parent_division_id' => 315,],
            ['division_id' => 502, 'division_name_ar' => 'قسم الصيانة الكهربائية', 'division_name_en' => 'Electrical Maintenance Department', 'parent_division_id' => 326,],
            ['division_id' => 506, 'division_name_ar' => 'قسم الحام', 'division_name_en' => 'Welding Department', 'parent_division_id' => 329,],
            ['division_id' => 507, 'division_name_ar' => 'قسم النجارة', 'division_name_en' => 'Carpentry Department', 'parent_division_id' => 103,],
            ['division_id' => 508, 'division_name_ar' => 'قسم الدهانات', 'division_name_en' => 'Painting Department', 'parent_division_id' => 329,],
            ['division_id' => 509, 'division_name_ar' => 'قسم الخراطة', 'division_name_en' => 'Lathe Department', 'parent_division_id' => 329,],
            ['division_id' => 529, 'division_name_ar' => 'صيانة مرافق', 'division_name_en' => 'Facility Maintenance', 'parent_division_id' => 329,],
            ['division_id' => 601, 'division_name_ar' => 'اختبارات الورنيش', 'division_name_en' => 'Varnish Testing', 'parent_division_id' => 436,],
            ['division_id' => 602, 'division_name_ar' => 'مراجعة الورنيش', 'division_name_en' => 'Varnish Review', 'parent_division_id' => 436,],
            ['division_id' => 610, 'division_name_ar' => 'سحب', 'division_name_en' => 'Pulling', 'parent_division_id' => 248,],
            ['division_id' => 611, 'division_name_ar' => 'جدل', 'division_name_en' => 'Stretching', 'parent_division_id' => 248,],
            ['division_id' => 612, 'division_name_ar' => 'عزل', 'division_name_en' => 'Insulation', 'parent_division_id' => 249,],
            ['division_id' => 613, 'division_name_ar' => 'غلاف', 'division_name_en' => 'Sheathing', 'parent_division_id' => 249,],
            ['division_id' => 614, 'division_name_ar' => 'تسليح', 'division_name_en' => 'Reinforcement', 'parent_division_id' => 250,],
            ['division_id' => 615, 'division_name_ar' => 'تجميع', 'division_name_en' => 'Assembly', 'parent_division_id' => 250,],
            ['division_id' => 616, 'division_name_ar' => 'تقطيع', 'division_name_en' => 'Cutting', 'parent_division_id' => 621,],
            ['division_id' => 617, 'division_name_ar' => 'قسم المراجعة', 'division_name_en' => 'Review Department', 'parent_division_id' => 208,],
            ['division_id' => 619, 'division_name_ar' => 'قسم الصيانة الكهربائية', 'division_name_en' => 'Electrical Maintenance Department', 'parent_division_id' => 216,],
            ['division_id' => 620, 'division_name_ar' => 'إدارة الأمن الإدارى', 'division_name_en' => 'Administrative Security Department', 'parent_division_id' => 3,],
            ['division_id' => 621, 'division_name_ar' => 'قسم التقطيع و اللفات', 'division_name_en' => 'Cutting and Rolling Department', 'parent_division_id' => 208,],
            ['division_id' => 622, 'division_name_ar' => 'تأهيل مهنى', 'division_name_en' => 'Vocational Qualification', 'parent_division_id' => 2,],
            ['division_id' => 623, 'division_name_ar' => 'اسكراب مصنع المنخفض', 'division_name_en' => 'Low Factory Scrap', 'parent_division_id' => 58,],
            ['division_id' => 624, 'division_name_ar' => 'اسكراب مصنع المتوسط', 'division_name_en' => 'Middle Factory Scrap', 'parent_division_id' => 108,],
        ];

        // Use the following instead for mysql
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        //
        // for SQL: as in https://github.com/laravel/framework/issues/35401
        // DB::table('divisions')->delete();
        //
        // Use the following instead for sqlite
        // DB::statement('PRAGMA foreign_keys = OFF;');
        DB::table('divisions')->truncate();

        foreach ($divisions as $division) {
            Division::create($division);
        }

        // Use the following instead for mysql
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        //
        // Use the following instead for sqlite
        // DB::statement('PRAGMA foreign_keys = ON;');

        // Division::factory()->count(5)->create();
    }
}
