<?php

namespace Database\Seeders;

use App\Models\JobTitle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class JobTitleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $job_titles = [
            ['job_title_id' => 1, 'job_title_name_ar' => 'اخصائى دعم تطبيقات', 'job_title_name_en' => 'Application Support Specialist', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 2, 'job_title_name_ar' => 'اخصائى تخطيط', 'job_title_name_en' => 'Planning Specialist', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 3, 'job_title_name_ar' => 'اخصائى دعم فنى', 'job_title_name_en' => 'Technical Support Specialist', 'job_category_id' => 2, 'job_class' => 'White Collars',],
            ['job_title_id' => 4, 'job_title_name_ar' => 'اخصائى شحن وتصدير', 'job_title_name_en' => 'Shipping and Export Specialist', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 5, 'job_title_name_ar' => 'اخصائى موارد بشرية', 'job_title_name_en' => 'Human Resources Specialist', 'job_category_id' => 11, 'job_class' => 'White Collars',],
            ['job_title_id' => 6, 'job_title_name_ar' => 'اخصائى اول تخطيط', 'job_title_name_en' => 'Senior Planning Specialist', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 7, 'job_title_name_ar' => 'اخصائى مبيعات', 'job_title_name_en' => 'Sales Specialist', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 8, 'job_title_name_ar' => 'ادارى', 'job_title_name_en' => 'Administrator', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 9, 'job_title_name_ar' => 'ادارى شئون قانونية', 'job_title_name_en' => 'Legal Affairs Administrator', 'job_category_id' => 14, 'job_class' => 'White Collars',],
            ['job_title_id' => 10, 'job_title_name_ar' => 'مدير ادارى', 'job_title_name_en' => 'Administrative Manager', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 11, 'job_title_name_ar' => 'امين مخزن', 'job_title_name_en' => 'Warehouse Keeper', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 12, 'job_title_name_ar' => 'مندوب تشهيلات', 'job_title_name_en' => 'Facilities Representative', 'job_category_id' => 15, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 13, 'job_title_name_ar' => 'حارس امن', 'job_title_name_en' => 'Security Guard', 'job_category_id' => 7, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 14, 'job_title_name_ar' => 'رئيس قسم الشئون الادارية', 'job_title_name_en' => 'Head of Administrative Affairs Department', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 15, 'job_title_name_ar' => 'رئيس القسم المالى بالمصنع', 'job_title_name_en' => 'Head of the Factory Finance Department', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 16, 'job_title_name_ar' => 'رئيس حسابات المعرض', 'job_title_name_en' => 'Head of Exhibition Accounts', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 17, 'job_title_name_ar' => 'رئيس قسم البناشر', 'job_title_name_en' => 'Head of the Tire Shop Department', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 18, 'job_title_name_ar' => 'رئيس قسم التأمينات', 'job_title_name_en' => 'Head of the Insurance Department', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 19, 'job_title_name_ar' => 'رئيس قسم التجميع والتسليح', 'job_title_name_en' => 'Head of the Assembly and Arming Department', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 20, 'job_title_name_ar' => 'رئيس قسم التكاليف', 'job_title_name_en' => 'Head of the Costing Department', 'job_category_id' => 16, 'job_class' => 'White Collars',],
            ['job_title_id' => 21, 'job_title_name_ar' => 'رئيس قسم الحركة', 'job_title_name_en' => 'Head of the Movement Department', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 22, 'job_title_name_ar' => 'رئيس قسم السلامة والصحة المهنية', 'job_title_name_en' => 'Head of the Occupational Safety and Health Department', 'job_category_id' => 10, 'job_class' => 'White Collars',],
            ['job_title_id' => 23, 'job_title_name_ar' => 'رئيس قسم شئون العاملين', 'job_title_name_en' => 'Head of the Personnel Affairs Department', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 24, 'job_title_name_ar' => 'رئيس مجموعة التوريدات', 'job_title_name_en' => 'Head of the Supplies Group', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 25, 'job_title_name_ar' => 'رئيس وردية نجارة', 'job_title_name_en' => 'Head of the Carpentry Shift', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 26, 'job_title_name_ar' => 'رئيس ورشة النجارة', 'job_title_name_en' => 'Head of the Carpentry Workshop', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 27, 'job_title_name_ar' => 'ساعى', 'job_title_name_en' => 'Courier', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 28, 'job_title_name_ar' => 'سائق درجة اولى', 'job_title_name_en' => 'First Class Driver', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 29, 'job_title_name_ar' => 'سائق درجة ثالثة', 'job_title_name_en' => 'Third Class Driver', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 30, 'job_title_name_ar' => 'سائق درجة ثانية', 'job_title_name_en' => 'Second Class Driver', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 31, 'job_title_name_ar' => 'سائق كلارك', 'job_title_name_en' => 'Clark Driver', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 32, 'job_title_name_ar' => 'سباك', 'job_title_name_en' => 'Plumber', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 33, 'job_title_name_ar' => 'سكرتير', 'job_title_name_en' => 'Secretary', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 34, 'job_title_name_ar' => 'عامل شحن', 'job_title_name_en' => 'Shipping Worker', 'job_category_id' => 18, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 35, 'job_title_name_ar' => 'عامل مخزن', 'job_title_name_en' => 'Warehouse Worker', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 36, 'job_title_name_ar' => 'فنى نجار', 'job_title_name_en' => 'Carpenter Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 37, 'job_title_name_ar' => 'عامل خدمات', 'job_title_name_en' => 'Service Worker', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 38, 'job_title_name_ar' => 'فنى اختبارات', 'job_title_name_en' => 'Test Technician', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 39, 'job_title_name_ar' => 'فنى انتاج', 'job_title_name_en' => 'Production Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 40, 'job_title_name_ar' => 'فنى صيانة كهربائية', 'job_title_name_en' => 'Electrical Maintenance Technician', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 41, 'job_title_name_ar' => 'فنى تبريد وتكييف', 'job_title_name_en' => 'Refrigeration and Air Conditioning Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 42, 'job_title_name_ar' => 'فنى تركيبات كهربائية', 'job_title_name_en' => 'Electrical Installation Technician', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 43, 'job_title_name_ar' => 'فنى اول صيانة كهربائية', 'job_title_name_en' => 'First Electrical Maintenance Technician', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 44, 'job_title_name_ar' => 'فنى كاوتش', 'job_title_name_en' => 'Type Technician', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 45, 'job_title_name_ar' => 'فني صيانة ميكانيكية', 'job_title_name_en' => 'Mechanical Maintenance Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 46, 'job_title_name_ar' => 'فنى نجار', 'job_title_name_en' => 'Carpenter Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 47, 'job_title_name_ar' => 'فنى اول خراطه', 'job_title_name_en' => 'First Lathe Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 48, 'job_title_name_ar' => 'فنى اول دهانات', 'job_title_name_en' => 'First Paint Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 49, 'job_title_name_ar' => 'فنى اول مرافق', 'job_title_name_en' => 'First Facilities Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 50, 'job_title_name_ar' => 'فنى اول صيانة ميكانيكية', 'job_title_name_en' => 'First Mechanical Maintenance Technician', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 51, 'job_title_name_ar' => 'فنى اول ميكانيكى سيارات', 'job_title_name_en' => 'First Auto Mechanic Technician', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 52, 'job_title_name_ar' => 'فنى اول نجار', 'job_title_name_en' => 'First Carpenter Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 53, 'job_title_name_ar' => 'فنى خراطه', 'job_title_name_en' => 'Lathe Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 54, 'job_title_name_ar' => 'فنى دهانات', 'job_title_name_en' => 'Painting Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 55, 'job_title_name_ar' => 'فنى كهربائى سيارات', 'job_title_name_en' => 'Auto Electrician', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 56, 'job_title_name_ar' => 'فنى لحام', 'job_title_name_en' => 'Welding Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 57, 'job_title_name_ar' => 'مترجم', 'job_title_name_en' => 'Translator', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 58, 'job_title_name_ar' => 'محاسب', 'job_title_name_en' => 'Accountant', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 59, 'job_title_name_ar' => 'محاسب تحصيلات', 'job_title_name_en' => 'Collection Accountant', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 60, 'job_title_name_ar' => 'محاسب تكاليف', 'job_title_name_en' => 'Cost Accountant', 'job_category_id' => 16, 'job_class' => 'White Collars',],
            ['job_title_id' => 61, 'job_title_name_ar' => 'محاسب عملاء', 'job_title_name_en' => 'Customs Accountant', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 62, 'job_title_name_ar' => 'مخلص جمارك', 'job_title_name_en' => 'Data Entry', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 63, 'job_title_name_ar' => 'مدخل بيانات', 'job_title_name_en' => 'Planning Manager', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 64, 'job_title_name_ar' => 'مدير التخطيط', 'job_title_name_en' => 'Accounts Manager', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 65, 'job_title_name_ar' => 'مدير الحسابات', 'job_title_name_en' => 'Legal Affairs Manager', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 66, 'job_title_name_ar' => 'مدير الشئون القانونية', 'job_title_name_en' => 'Local Purchasing Manager', 'job_category_id' => 14, 'job_class' => 'White Collars',],
            ['job_title_id' => 67, 'job_title_name_ar' => 'مدير المشتريات المحلية', 'job_title_name_en' => 'HR Manager', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 68, 'job_title_name_ar' => 'مدير الموارد البشرية', 'job_title_name_en' => 'Systems Manager', 'job_category_id' => 11, 'job_class' => 'White Collars',],
            ['job_title_id' => 69, 'job_title_name_ar' => 'مدير النظم', 'job_title_name_en' => 'Production Manager', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 70, 'job_title_name_ar' => 'مدير انتاج', 'job_title_name_en' => 'Quality Assurance Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 71, 'job_title_name_ar' => 'مدير توكيد الجودة', 'job_title_name_en' => 'Customer Service Manager', 'job_category_id' => 17, 'job_class' => 'White Collars',],
            ['job_title_id' => 72, 'job_title_name_ar' => 'مدير خدمة العملاء', 'job_title_name_en' => 'Electrical Maintenance Manager', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 73, 'job_title_name_ar' => 'مدير الصيانة الكهربائية', 'job_title_name_en' => 'General Maintenance Manager', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 74, 'job_title_name_ar' => 'مدير عام الصيانة', 'job_title_name_en' => 'General Factory Manager', 'job_category_id' => 3, 'job_class' => 'White Collars',],
            ['job_title_id' => 75, 'job_title_name_ar' => 'مدير عام المصانع', 'job_title_name_en' => 'General Factory Manager', 'job_category_id' => 23, 'job_class' => 'White Collars',],
            ['job_title_id' => 76, 'job_title_name_ar' => 'مدير عام المصنع', 'job_title_name_en' => 'Finance Manager', 'job_category_id' => 23, 'job_class' => 'White Collars',],
            ['job_title_id' => 77, 'job_title_name_ar' => 'المدير المالى', 'job_title_name_en' => 'Export Manager', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 78, 'job_title_name_ar' => 'مدير التصدير', 'job_title_name_en' => 'Region Export Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 79, 'job_title_name_ar' => 'مدير تصدير منطقه', 'job_title_name_en' => 'Area Export Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 80, 'job_title_name_ar' => 'مدير المخازن', 'job_title_name_en' => 'Warehouse Manager', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 81, 'job_title_name_ar' => 'مدير نظم المعلومات', 'job_title_name_en' => 'Information Systems Manager', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 82, 'job_title_name_ar' => 'مراقب شحن', 'job_title_name_en' => 'Shipping Supervisor', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 83, 'job_title_name_ar' => 'مراقب مخازن', 'job_title_name_en' => 'Warehouse Supervisor', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 84, 'job_title_name_ar' => 'مراقب منتج نهائي', 'job_title_name_en' => 'Final Product Supervisor', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 85, 'job_title_name_ar' => 'مراقب داخلى', 'job_title_name_en' => 'Internal Supervisor', 'job_category_id' => 17, 'job_class' => 'White Collars',],
            ['job_title_id' => 86, 'job_title_name_ar' => 'مساعد رئيس قسم الحسابات', 'job_title_name_en' => 'Assistant Head of Accounting Department', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 87, 'job_title_name_ar' => 'مساعد فنى', 'job_title_name_en' => 'Technical Assistant', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 88, 'job_title_name_ar' => 'مساعد فنى مراجعه', 'job_title_name_en' => 'Review Technical Assistant', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 89, 'job_title_name_ar' => 'مساعد فنى ميكانيكى سيارات', 'job_title_name_en' => 'Auto Mechanic Technical Assistant', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 90, 'job_title_name_ar' => 'مساعد مراقب جودة', 'job_title_name_en' => 'Quality Control Assistant', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 91, 'job_title_name_ar' => 'مسئول تنسيق', 'job_title_name_en' => 'Coordination Officer', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 92, 'job_title_name_ar' => 'مسئول دفاع مدنى', 'job_title_name_en' => 'Civil Defense Officer', 'job_category_id' => 10, 'job_class' => 'White Collars',],
            ['job_title_id' => 93, 'job_title_name_ar' => 'مسئول تصدير', 'job_title_name_en' => 'Export Officer', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 94, 'job_title_name_ar' => 'مسئول مشتريات', 'job_title_name_en' => 'Purchasing Officer', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 95, 'job_title_name_ar' => 'مشرف الحركة', 'job_title_name_en' => 'Movement Supervisor', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 96, 'job_title_name_ar' => 'مشرف امن', 'job_title_name_en' => 'Security Supervisor', 'job_category_id' => 7, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 97, 'job_title_name_ar' => 'مشرف انتاج', 'job_title_name_en' => 'Production Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 98, 'job_title_name_ar' => 'مشرف جدل', 'job_title_name_en' => 'Controller Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 99, 'job_title_name_ar' => 'مشرف سحب', 'job_title_name_en' => 'Withdrawal Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 100, 'job_title_name_ar' => 'مشرف صيانة ميكانيكية', 'job_title_name_en' => 'Mechanical Maintenance Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 101, 'job_title_name_ar' => 'مشرف مبيعات', 'job_title_name_en' => 'Sales Supervisor', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 102, 'job_title_name_ar' => 'مشرف مرافق', 'job_title_name_en' => 'Facilities Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 103, 'job_title_name_ar' => 'مشرف صيانة ميكانيكية', 'job_title_name_en' => 'Mechanical Maintenance Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 104, 'job_title_name_ar' => 'مشرف نظافة', 'job_title_name_en' => 'Cleaning Supervisor', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 105, 'job_title_name_ar' => 'مشرف وردية', 'job_title_name_en' => 'Shift Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 106, 'job_title_name_ar' => 'مشرف ورشة الفليرات', 'job_title_name_en' => 'Filler Workshop Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 107, 'job_title_name_ar' => 'مهندس انتاج', 'job_title_name_en' => 'Production Engineer', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 108, 'job_title_name_ar' => 'مهندس اول صيانة كهربائية', 'job_title_name_en' => 'Senior Electrical Maintenance Engineer', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 109, 'job_title_name_ar' => 'مهندس جودة', 'job_title_name_en' => 'Quality Engineer', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 110, 'job_title_name_ar' => 'مهندس صيانة كهربائية', 'job_title_name_en' => 'Electrical Maintenance Engineer', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 111, 'job_title_name_ar' => 'مهندس مبيعات', 'job_title_name_en' => 'Sales Engineer', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 112, 'job_title_name_ar' => 'مهندس مواصفات', 'job_title_name_en' => 'Specifications Engineer', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 113, 'job_title_name_ar' => 'نائب مدير الانتاج', 'job_title_name_en' => 'Deputy Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 114, 'job_title_name_ar' => 'مدير تطوير اعمال', 'job_title_name_en' => 'Business Development Manager', 'job_category_id' => 21, 'job_class' => 'White Collars',],
            ['job_title_id' => 115, 'job_title_name_ar' => 'مهندس تسويق ماقبل البيع', 'job_title_name_en' => 'Pre-Sales Marketing Engineer', 'job_category_id' => 21, 'job_class' => 'White Collars',],
            ['job_title_id' => 116, 'job_title_name_ar' => 'مدير عام الموارد البشرية', 'job_title_name_en' => 'General Manager of Human Resources', 'job_category_id' => 11, 'job_class' => 'White Collars',],
            ['job_title_id' => 118, 'job_title_name_ar' => 'فنى رصاص', 'job_title_name_en' => 'Lead Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 119, 'job_title_name_ar' => 'رئيس قسم الصيانة الكهربائية', 'job_title_name_en' => 'Head of Electrical Maintenance Department', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 120, 'job_title_name_ar' => 'محامى', 'job_title_name_en' => 'Lawyer', 'job_category_id' => 14, 'job_class' => 'White Collars',],
            ['job_title_id' => 121, 'job_title_name_ar' => 'مدير مبيعات المشاريع', 'job_title_name_en' => 'Project Sales Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 122, 'job_title_name_ar' => 'مهندس صيانة ميكانيكية', 'job_title_name_en' => 'Mechanical Maintenance Engineer', 'job_category_id' => 5, 'job_class' => 'White Collars',],
            ['job_title_id' => 123, 'job_title_name_ar' => 'فنى تسليح', 'job_title_name_en' => 'Reinforcement Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 124, 'job_title_name_ar' => 'رئيس قسم السحب', 'job_title_name_en' => 'Head of Drawing Department', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 125, 'job_title_name_ar' => 'فنى سحب', 'job_title_name_en' => 'Drawing Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 126, 'job_title_name_ar' => 'فنى جدل', 'job_title_name_en' => 'Weaving Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 127, 'job_title_name_ar' => 'فنى تجميع', 'job_title_name_en' => 'Assembly Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 128, 'job_title_name_ar' => 'فنى غلاف', 'job_title_name_en' => 'Covering Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 129, 'job_title_name_ar' => 'فنى عزل', 'job_title_name_en' => 'Insulation Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 130, 'job_title_name_ar' => 'فنى مراجعة', 'job_title_name_en' => 'Audit Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 131, 'job_title_name_ar' => 'المستشار المالى', 'job_title_name_en' => 'Financial Advisor', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 132, 'job_title_name_ar' => 'مدير حسابات المبيعات', 'job_title_name_en' => 'Sales Account Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 133, 'job_title_name_ar' => 'رئيس قسم الأمن', 'job_title_name_en' => 'Security Section Head', 'job_category_id' => 7, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 134, 'job_title_name_ar' => 'مدير عام تكنولوجيا المعلومات', 'job_title_name_en' => 'IT General Manager', 'job_category_id' => 2, 'job_class' => 'White Collars',],
            ['job_title_id' => 135, 'job_title_name_ar' => 'اخصائى اول موارد بشرية', 'job_title_name_en' => 'HR Senior Specialist', 'job_category_id' => 11, 'job_class' => 'White Collars',],
            ['job_title_id' => 136, 'job_title_name_ar' => 'مدير المشتريات الخارجية', 'job_title_name_en' => 'External Purchasing Manager', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 137, 'job_title_name_ar' => 'مدير الجودة', 'job_title_name_en' => 'Quality Manager', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 138, 'job_title_name_ar' => 'مدير عام العمليات', 'job_title_name_en' => 'Operations General Manager', 'job_category_id' => 23, 'job_class' => 'White Collars',],
            ['job_title_id' => 139, 'job_title_name_ar' => 'رئيس قسم الصيانة الميكانيكية', 'job_title_name_en' => 'Head of Mechanical Maintenance Department', 'job_category_id' => 5, 'job_class' => 'White Collars',],
            ['job_title_id' => 140, 'job_title_name_ar' => 'مسئول شئون عاملين', 'job_title_name_en' => 'Personnel Affairs Officer', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 141, 'job_title_name_ar' => 'ادارى اسكراب', 'job_title_name_en' => 'Scrap Administrator', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 142, 'job_title_name_ar' => 'اخصائى مشتريات', 'job_title_name_en' => 'Purchasing Specialist', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 143, 'job_title_name_ar' => 'اخصائى تسليمات', 'job_title_name_en' => 'Delivery Specialist', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 144, 'job_title_name_ar' => 'مهندس تخطيط', 'job_title_name_en' => 'Planning Engineer', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 145, 'job_title_name_ar' => 'تأهيل مهنى 5%', 'job_title_name_en' => '5% Vocational Qualification', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 146, 'job_title_name_ar' => 'مشرف بوفيه', 'job_title_name_en' => 'Buffet Supervisor', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 147, 'job_title_name_ar' => 'مشرف مخازن الاسكراب', 'job_title_name_en' => 'Scrap Warehouse Supervisor', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 148, 'job_title_name_ar' => 'فنى CVL', 'job_title_name_en' => 'CVL Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 149, 'job_title_name_ar' => 'فنى انتاج تليفونات', 'job_title_name_en' => 'Telephone Production Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 150, 'job_title_name_ar' => 'فنى تقطيع', 'job_title_name_en' => 'Cutting Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 151, 'job_title_name_ar' => 'مدير انتاج العزل والغلاف', 'job_title_name_en' => 'Insulation and Cover Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 152, 'job_title_name_ar' => 'مدير انتاج المعادن', 'job_title_name_en' => 'Metal Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 153, 'job_title_name_ar' => 'مدير انتاج التجميع والتسليح', 'job_title_name_en' => 'Assembly and Reinforcement Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 154, 'job_title_name_ar' => 'مدير انتاج الورنيش', 'job_title_name_en' => 'Varnish Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 155, 'job_title_name_ar' => 'مدير انتاج المراجعة', 'job_title_name_en' => 'Review Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 156, 'job_title_name_ar' => 'مدير انتاج التليفونات', 'job_title_name_en' => 'Telephone Production Manager', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 157, 'job_title_name_ar' => 'مشرف بناشر', 'job_title_name_en' => 'Publisher Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 158, 'job_title_name_ar' => 'مشرف مراجعة', 'job_title_name_en' => 'Review Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 159, 'job_title_name_ar' => 'مهندس مشتريات', 'job_title_name_en' => 'Purchasing Engineer', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 160, 'job_title_name_ar' => 'مشرف عزل وغلاف', 'job_title_name_en' => 'Insulation and Covering Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 161, 'job_title_name_ar' => 'مشرف تقطيع', 'job_title_name_en' => 'Cutting Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 162, 'job_title_name_ar' => 'مشرف تجميع وتسليح', 'job_title_name_en' => 'Assembly and Reinforcement Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 163, 'job_title_name_ar' => 'مشرف ورنيش', 'job_title_name_en' => 'Varnish Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 164, 'job_title_name_ar' => 'مشرف جودة ورنيش', 'job_title_name_en' => 'Varnish Quality Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 165, 'job_title_name_ar' => 'مشرف اختبارات', 'job_title_name_en' => 'Testing Supervisor', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 166, 'job_title_name_ar' => 'رئيس قسم الشئون القانونية بالمصنع', 'job_title_name_en' => 'Head of Legal Affairs Department in the Factory', 'job_category_id' => 14, 'job_class' => 'White Collars',],
            ['job_title_id' => 167, 'job_title_name_ar' => 'مشرف فوركلفت', 'job_title_name_en' => 'Forklift Supervisor', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 168, 'job_title_name_ar' => 'فنى ميكانيكى سيارات', 'job_title_name_en' => 'Auto Mechanic Technician', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 169, 'job_title_name_ar' => 'مشرف صيانة كهربائية', 'job_title_name_en' => 'Electrical Maintenance Supervisor', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 170, 'job_title_name_ar' => 'مشرف تبريد وتكييف', 'job_title_name_en' => 'Refrigeration and Air Conditioning Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 171, 'job_title_name_ar' => 'مشرف دهانات', 'job_title_name_en' => 'Painting Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 172, 'job_title_name_ar' => 'مشرف نجارة', 'job_title_name_en' => 'Carpentry Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 173, 'job_title_name_ar' => 'منسق ومشرف عام تخطيط', 'job_title_name_en' => 'General Planning Coordinator and Supervisor', 'job_category_id' => 8, 'job_class' => 'White Collars',],
            ['job_title_id' => 174, 'job_title_name_ar' => 'رئيس قسم الاختبارات', 'job_title_name_en' => 'Head of Testing Department', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 175, 'job_title_name_ar' => 'مشرف مخازن الخامات', 'job_title_name_en' => 'Material Stores Supervisor', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 176, 'job_title_name_ar' => 'مشرف مخازن قطع الغيار', 'job_title_name_en' => 'Spare Parts Stores Supervisor', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 177, 'job_title_name_ar' => 'مسئول مبيعات', 'job_title_name_en' => 'Sales Officer', 'job_category_id' => 20, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 178, 'job_title_name_ar' => 'مسئول مبيعات المشاريع', 'job_title_name_en' => 'Project Sales Officer', 'job_category_id' => 20, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 179, 'job_title_name_ar' => 'رئيس قسم الشبكات', 'job_title_name_en' => 'Head of Networks Department', 'job_category_id' => 2, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 180, 'job_title_name_ar' => 'مشرف CVL', 'job_title_name_en' => 'CVL Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 181, 'job_title_name_ar' => 'رئيس قسم التركيبات', 'job_title_name_en' => 'Head of Installations Department', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 182, 'job_title_name_ar' => 'فنى اول لحام', 'job_title_name_en' => 'Senior Welding Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 183, 'job_title_name_ar' => 'رئيس قسم التقطيع واللفات', 'job_title_name_en' => 'Head of Cutting and Rolling Department', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 184, 'job_title_name_ar' => 'مهندس قسم النجارة', 'job_title_name_en' => 'Carpentry Department Engineer', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 185, 'job_title_name_ar' => 'امين مخزن الاسكراب', 'job_title_name_en' => 'Scrap Storekeeper', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 186, 'job_title_name_ar' => 'مشرف ميكانيكى سيارات', 'job_title_name_en' => 'Auto Mechanic Supervisor', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 187, 'job_title_name_ar' => 'مدير اول حسابات المبيعات', 'job_title_name_en' => 'Senior Sales Accounts Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 188, 'job_title_name_ar' => 'رئيس وردية اختبارات', 'job_title_name_en' => 'Test Shift Leader', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 189, 'job_title_name_ar' => 'رئيس قسم المواصفات الفنية', 'job_title_name_en' => 'Head of Technical Specifications Department', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 190, 'job_title_name_ar' => 'عامل خدمات (زراعة)', 'job_title_name_en' => 'Service Worker (Agriculture)', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 191, 'job_title_name_ar' => 'رئيس قسم الجدل', 'job_title_name_en' => 'Head of Debugging Department', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 192, 'job_title_name_ar' => 'فنى دهانات ( دوكو سيارات )', 'job_title_name_en' => 'Paint Technician (Car Paint)', 'job_category_id' => 6, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 194, 'job_title_name_ar' => 'فنى انتاج', 'job_title_name_en' => 'Production Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 195, 'job_title_name_ar' => 'مدير مبيعات', 'job_title_name_en' => 'Sales Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 196, 'job_title_name_ar' => 'متطور برمجيات', 'job_title_name_en' => 'Software Developer', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 197, 'job_title_name_ar' => 'مراقب جودة', 'job_title_name_en' => 'Quality Controller', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 198, 'job_title_name_ar' => 'اخصائى اول مشتريات خارجية', 'job_title_name_en' => 'Senior External Purchasing Specialist', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 199, 'job_title_name_ar' => 'مشرف انتاج ورنيش', 'job_title_name_en' => 'Varnish Production Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 200, 'job_title_name_ar' => 'منسق مبيعات', 'job_title_name_en' => 'Sales Coordinator', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 201, 'job_title_name_ar' => 'اخصائى شئون عاملين', 'job_title_name_en' => 'Personnel Affairs Specialist', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 202, 'job_title_name_ar' => 'رئيس قسم العزل والغلاف', 'job_title_name_en' => 'Head of Insulation and Covering Department', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 203, 'job_title_name_ar' => 'مدير عام الإدارة الهندسية', 'job_title_name_en' => 'General Manager of Engineering Department', 'job_category_id' => 3, 'job_class' => 'White Collars',],
            ['job_title_id' => 204, 'job_title_name_ar' => 'مشرف عام', 'job_title_name_en' => 'General Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 205, 'job_title_name_ar' => 'مشرف تسليح وسكرين', 'job_title_name_en' => 'Reinforcement and Screen Supervisor', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 206, 'job_title_name_ar' => 'اخصائى قواعد بيانات', 'job_title_name_en' => 'Database Specialist', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 207, 'job_title_name_ar' => 'مندوب تحصيلات', 'job_title_name_en' => 'Collection Representative', 'job_category_id' => 15, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 208, 'job_title_name_ar' => 'Help Desk', 'job_title_name_en' => 'Help Desk', 'job_category_id' => 2, 'job_class' => 'White Collars',],
            ['job_title_id' => 209, 'job_title_name_ar' => 'مراقب مالى', 'job_title_name_en' => 'Financial Controller', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 210, 'job_title_name_ar' => 'سائق رخصة خاصه', 'job_title_name_en' => 'Private License Driver', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 211, 'job_title_name_ar' => 'عامل خدمات (بوفيه)', 'job_title_name_en' => 'Service Worker (Buffet)', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 212, 'job_title_name_ar' => 'مدير تسويق ما قبل البيع', 'job_title_name_en' => 'Pre-Sales Marketing Manager', 'job_category_id' => 21, 'job_class' => 'White Collars',],
            ['job_title_id' => 213, 'job_title_name_ar' => 'مدير المواصفات الفنية', 'job_title_name_en' => 'Technical Specifications Manager', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 214, 'job_title_name_ar' => 'مدير التكاليف', 'job_title_name_en' => 'Cost Manager', 'job_category_id' => 16, 'job_class' => 'White Collars',],
            ['job_title_id' => 215, 'job_title_name_ar' => 'مدير مكتب العضو المنتدب', 'job_title_name_en' => 'Managing Director\'s Office Manager', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 216, 'job_title_name_ar' => 'مدير منافذ البيع', 'job_title_name_en' => 'Sales Outlets Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 217, 'job_title_name_ar' => 'مدير صيانة معدات الحركة والنقل', 'job_title_name_en' => 'Motor Vehicle Maintenance Manager', 'job_category_id' => 6, 'job_class' => 'White Collars',],
            ['job_title_id' => 218, 'job_title_name_ar' => 'مدير عام سلسلة الامدادات', 'job_title_name_en' => 'Supply Chain General Manager', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 219, 'job_title_name_ar' => 'المدير التجارى', 'job_title_name_en' => 'Commercial Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 220, 'job_title_name_ar' => 'مهندس كيميائى', 'job_title_name_en' => 'Chemical Engineer', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 221, 'job_title_name_ar' => 'رئيس قسم النجارة بالمصانع', 'job_title_name_en' => 'Head of Carpentry Department in Factories', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 222, 'job_title_name_ar' => 'مدير الامن الادارى', 'job_title_name_en' => 'Administrative Security Manager', 'job_category_id' => 7, 'job_class' => 'White Collars',],
            ['job_title_id' => 223, 'job_title_name_ar' => 'مدير السلامة والصحة المهنية', 'job_title_name_en' => 'Occupational Safety and Health Manager', 'job_category_id' => 10, 'job_class' => 'White Collars',],
            ['job_title_id' => 224, 'job_title_name_ar' => 'رسام هندسى', 'job_title_name_en' => 'Engineering Draftsman', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 225, 'job_title_name_ar' => 'مدير مشروعات', 'job_title_name_en' => 'Project Manager', 'job_category_id' => 3, 'job_class' => 'White Collars',],
            ['job_title_id' => 226, 'job_title_name_ar' => 'مشرف تركيبات كهربائية', 'job_title_name_en' => 'Electrical Installations Supervisor', 'job_category_id' => 4, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 227, 'job_title_name_ar' => 'مساعد امين مخزن', 'job_title_name_en' => 'Assistant Storekeeper', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 228, 'job_title_name_ar' => 'رئيس قسم صيانة معدات النقل والحركة', 'job_title_name_en' => 'Head of Maintenance Department of Motor Vehicles', 'job_category_id' => 6, 'job_class' => 'White Collars',],
            ['job_title_id' => 229, 'job_title_name_ar' => 'رئيس قسم الفليرات', 'job_title_name_en' => 'Head of Flares Department', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 230, 'job_title_name_ar' => 'مساعد فنى سلامه وصحه مهنية', 'job_title_name_en' => 'Assistant Technical Safety and Health', 'job_category_id' => 10, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 231, 'job_title_name_ar' => 'مشرف عمال الخدمات', 'job_title_name_en' => 'Service Workers Supervisor', 'job_category_id' => 13, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 232, 'job_title_name_ar' => 'فنى فرزجى', 'job_title_name_en' => 'Frameworker Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 233, 'job_title_name_ar' => 'مدير عام المبيعات والتسويق', 'job_title_name_en' => 'General Manager of Sales and Marketing', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 234, 'job_title_name_ar' => 'مدير مبيعات البترول', 'job_title_name_en' => 'Petroleum Sales Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 235, 'job_title_name_ar' => 'مدير المشتريات المحلية والمخازن', 'job_title_name_en' => 'Local Purchasing and Warehouse Manager', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 236, 'job_title_name_ar' => 'رئيس قسم المشتريات الخارجية', 'job_title_name_en' => 'Head of External Purchasing Department', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 237, 'job_title_name_ar' => 'رئيس قسم المشتريات والمخازن بالمصانع', 'job_title_name_en' => 'Head of Purchasing and Warehouse Department in Factories', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 238, 'job_title_name_ar' => 'رئيس قسم المراجعة الداخلية وضبط الوثائق', 'job_title_name_en' => 'Head of Internal Audit and Document Control Department', 'job_category_id' => 17, 'job_class' => 'White Collars',],
            ['job_title_id' => 239, 'job_title_name_ar' => 'Corporate Treasury Director', 'job_title_name_en' => 'Corporate Treasury Director', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 240, 'job_title_name_ar' => 'Technical Engineer Supervisor', 'job_title_name_en' => 'Technical Engineer Supervisor', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 241, 'job_title_name_ar' => 'رئيس قسم الصيانة الوقائية', 'job_title_name_en' => 'Head of Preventive Maintenance', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 242, 'job_title_name_ar' => 'فنى سلامة وصحة مهنية', 'job_title_name_en' => 'Occupational Health and Safety Technician', 'job_category_id' => 10, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 243, 'job_title_name_ar' => 'مهندس كهرباء (تحت التدريب)', 'job_title_name_en' => 'Electrical Engineer (under training)', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 244, 'job_title_name_ar' => 'Senior IT Engineer', 'job_title_name_en' => 'Senior IT Engineer', 'job_category_id' => 2, 'job_class' => 'White Collars',],
            ['job_title_id' => 245, 'job_title_name_ar' => 'منسق موارد بشرية', 'job_title_name_en' => 'Human Resources Coordinator', 'job_category_id' => 11, 'job_class' => 'White Collars',],
            ['job_title_id' => 246, 'job_title_name_ar' => 'Senior Marketing Communication Lead', 'job_title_name_en' => 'Senior Marketing Communication Lead', 'job_category_id' => 21, 'job_class' => 'White Collars',],
            ['job_title_id' => 247, 'job_title_name_ar' => 'Procurement Section Head', 'job_title_name_en' => 'Procurement Section Head', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 248, 'job_title_name_ar' => 'رئيس قسم الاسكرين', 'job_title_name_en' => 'Screen Section Head', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 249, 'job_title_name_ar' => 'رئيس قسم السحب والجدل', 'job_title_name_en' => 'Head of Withdrawal and Debugging Section', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 250, 'job_title_name_ar' => 'مدير التدريب', 'job_title_name_en' => 'Training Manager', 'job_category_id' => 12, 'job_class' => 'White Collars',],
            ['job_title_id' => 251, 'job_title_name_ar' => 'مدير الصيانة', 'job_title_name_en' => 'Maintenance Manager', 'job_category_id' => 3, 'job_class' => 'White Collars',],
            ['job_title_id' => 252, 'job_title_name_ar' => 'ادارى اول', 'job_title_name_en' => 'Senior Administrator', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 253, 'job_title_name_ar' => 'مشرف مخازن الخامات والاسكراب', 'job_title_name_en' => 'Raw Materials and Scrap Warehouse Supervisor', 'job_category_id' => 22, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 254, 'job_title_name_ar' => 'رئيس قسم الاسكراب', 'job_title_name_en' => 'Scrap Section Head', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 255, 'job_title_name_ar' => 'مهندس اول مبيعات', 'job_title_name_en' => 'Senior Sales Engineer', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 256, 'job_title_name_ar' => 'مدير عام الجودة وتوكيد الجودة', 'job_title_name_en' => 'General Manager of Quality and Quality Assurance', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 257, 'job_title_name_ar' => 'Information Systems Manager', 'job_title_name_en' => 'Information Systems Manager', 'job_category_id' => 1, 'job_class' => 'White Collars',],
            ['job_title_id' => 258, 'job_title_name_ar' => 'فنى اول', 'job_title_name_en' => 'Senior Technician', 'job_category_id' => 24, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 259, 'job_title_name_ar' => 'Banking Operation Section Head', 'job_title_name_en' => 'Banking Operation Section Head', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 260, 'job_title_name_ar' => 'مدير حسابات العملاء والتحصيلات', 'job_title_name_en' => 'Customer Accounts and Collections Manager', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 261, 'job_title_name_ar' => 'مدير حسابات الموردين', 'job_title_name_en' => 'Supplier Accounts Manager', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 262, 'job_title_name_ar' => 'محاسب اول', 'job_title_name_en' => 'Senior Accountant', 'job_category_id' => 15, 'job_class' => 'White Collars',],
            ['job_title_id' => 263, 'job_title_name_ar' => 'مدير عام مبيعات الكهرباء', 'job_title_name_en' => 'General Manager of Electricity Sales', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 264, 'job_title_name_ar' => 'مدير عام مبيعات الكهرباء والإتصالات', 'job_title_name_en' => 'General Manager of Electricity and Communications Sales', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 265, 'job_title_name_ar' => 'مدير الصيانة الكهربائية', 'job_title_name_en' => 'Electrical Maintenance Manager', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 266, 'job_title_name_ar' => 'اخصائى اول لوجيستيك', 'job_title_name_en' => 'Logistics Senior Specialist', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 267, 'job_title_name_ar' => 'منسق تسليمات وخدمة عملاء', 'job_title_name_en' => 'Delivery & Customer Service Coordinator', 'job_category_id' => 18, 'job_class' => 'White Collars',],
            ['job_title_id' => 268, 'job_title_name_ar' => 'مدير تحسين الجودة', 'job_title_name_en' => 'Quality Improvement Manager', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 269, 'job_title_name_ar' => 'مهندس اول صيانة ميكانيكية', 'job_title_name_en' => 'Senior Mechanical Maintenance Engineer', 'job_category_id' => 5, 'job_class' => 'White Collars',],
            ['job_title_id' => 270, 'job_title_name_ar' => 'مدير تخطيط الجودة', 'job_title_name_en' => 'Quality Planning Manager', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 271, 'job_title_name_ar' => 'فنى براده', 'job_title_name_en' => 'Refrigerator Technician', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 272, 'job_title_name_ar' => 'رئيس قسم التكاليف بالمصنع', 'job_title_name_en' => 'Head of Factory Costing Department', 'job_category_id' => 17, 'job_class' => 'White Collars',],
            ['job_title_id' => 273, 'job_title_name_ar' => 'رئيس قسم الخدمات اللوجيستية', 'job_title_name_en' => 'Head of Logistics Department', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 274, 'job_title_name_ar' => 'اخصائى اول شئون ادارية وعاملين', 'job_title_name_en' => 'Senior Specialist Administrative & Labor Affairs', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 275, 'job_title_name_ar' => 'نائب مدير الجودة', 'job_title_name_en' => 'Deputy Quality Manager', 'job_category_id' => 9, 'job_class' => 'White Collars',],
            ['job_title_id' => 276, 'job_title_name_ar' => 'رئيس قسم صيانة الأعطال والمعامل', 'job_title_name_en' => 'Head of Maintenance & Faults Department', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 277, 'job_title_name_ar' => 'منسق مشتريات ومشرف عام مخازن قطع الغيار', 'job_title_name_en' => 'Purchasing Coordinator & General Supervisor Spare Parts Warehouses', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 278, 'job_title_name_ar' => 'Design & Technical Manager', 'job_title_name_en' => 'Design & Technical Manager', 'job_category_id' => 19, 'job_class' => 'White Collars',],
            ['job_title_id' => 279, 'job_title_name_ar' => 'مهندس توكيد الجودة', 'job_title_name_en' => 'Quality Assurance Engineer', 'job_category_id' => 17, 'job_class' => 'White Collars',],
            ['job_title_id' => 280, 'job_title_name_ar' => 'مدير عام مبيعات المشاريع', 'job_title_name_en' => 'General Manager of Project Sales', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 281, 'job_title_name_ar' => 'رئيس قسم الشئون الادارية', 'job_title_name_en' => 'Head of Administrative Affairs Department', 'job_category_id' => 13, 'job_class' => 'White Collars',],
            ['job_title_id' => 282, 'job_title_name_ar' => 'Technical Support', 'job_title_name_en' => 'Technical Support', 'job_category_id' => 2, 'job_class' => 'White Collars',],
            ['job_title_id' => 283, 'job_title_name_ar' => 'رئيس قسم صيانة الالكترونيات', 'job_title_name_en' => 'Head of Electronics Maintenance Department', 'job_category_id' => 4, 'job_class' => 'White Collars',],
            ['job_title_id' => 284, 'job_title_name_ar' => 'مشرف جودة', 'job_title_name_en' => 'Quality Supervisor', 'job_category_id' => 9, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 285, 'job_title_name_ar' => 'HSE Senior Manager', 'job_title_name_en' => 'HSE Senior Manager', 'job_category_id' => 10, 'job_class' => 'White Collars',],
            ['job_title_id' => 286, 'job_title_name_ar' => 'رئيس قسم صيانة المرافق والورش', 'job_title_name_en' => 'Head of Facilities & Workshop Maintenance Department', 'job_category_id' => 5, 'job_class' => 'White Collars',],
            ['job_title_id' => 287, 'job_title_name_ar' => 'مشرف خراطه', 'job_title_name_en' => 'Lathe Supervisor', 'job_category_id' => 5, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 288, 'job_title_name_ar' => 'مراقب كاميرات', 'job_title_name_en' => 'Camera Supervisor', 'job_category_id' => 7, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 289, 'job_title_name_ar' => 'مساعد مراقب شحن', 'job_title_name_en' => 'Assistant Shipping Controller', 'job_category_id' => 18, 'job_class' => 'Blue Collars',],
            ['job_title_id' => 290, 'job_title_name_ar' => 'مدير عام التسويق', 'job_title_name_en' => 'General Manager Marketing', 'job_category_id' => 21, 'job_class' => 'White Collars',],
            ['job_title_id' => 291, 'job_title_name_ar' => 'رئيس قسم المعادن', 'job_title_name_en' => 'Head of Metals Department', 'job_category_id' => 24, 'job_class' => 'White Collars',],
            ['job_title_id' => 293, 'job_title_name_ar' => 'Foreign Procurement Specialist', 'job_title_name_en' => 'Foreign Procurement Specialist', 'job_category_id' => 22, 'job_class' => 'White Collars',],
            ['job_title_id' => 294, 'job_title_name_ar' => 'Business Head Commercial Manager', 'job_title_name_en' => 'Business Head Commercial Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 295, 'job_title_name_ar' => 'Sales Engineer', 'job_title_name_en' => 'Sales Engineer', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 296, 'job_title_name_ar' => 'Product Manager', 'job_title_name_en' => 'Product Manager', 'job_category_id' => 20, 'job_class' => 'White Collars',],
            ['job_title_id' => 297, 'job_title_name_ar' => 'اخصائى سلامة وصحة مهنية', 'job_title_name_en' => 'Occupational Safety and Health Specialist', 'job_category_id' => 10, 'job_class' => 'White Collars',],
        ];

        // Use the following instead for mysql
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        //
        // for SQL: as in https://github.com/laravel/framework/issues/35401
        // DB::table('job_titles')->delete();
        //
        // Use the following instead for sqlite
        // DB::statement('PRAGMA foreign_keys = OFF;');
        DB::table('job_titles')->truncate();

        foreach ($job_titles as $job_title) {
            JobTitle::create($job_title);
        }

        // Use the following instead for mysql
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        //
        // Use the following instead for sqlite
        // DB::statement('PRAGMA foreign_keys = ON;');

        // JobTitle::factory()->count(5)->create();
    }
}
